### ISSUE TITLE
Additional maintainers

### ISSUE THREAD

**Issue by mlondschien** [conda-forge/pyproximal-feedstock#1]
Hi @mrava87 

Thank you for your work on pyproximal. I just wanted to ping you to let you know that I took the liberty to add pyproximal to conda-forge. The package can now be installed with `conda install -c conda-forge pyproximal`. If you would like to be added as a maintainer to this feedstock, just open an issue with
```
@conda-forge-admin, please add user @mrava87
```
in the title.

**Comment by mrava87** [comment]
Really nice, thanks a lot! We already have our `pylops` package in conda-forge, great to have also pyproximal :D 

I'll add an issue so I can also follow the status of the Conda-forge package when we push new versions
